#!/bin/bash
#Author: Fikris Technologies
#Purpose: Interactive menu to check status of, start, or stop a SAP ASE
#         instance (database engine + backup server), with a confirmation
#         gate before any action against a Production SID.
trap '{ echo "Caught SIGINT, as you have pressed ctrl+c, exiting from the script" ;  exit 1; }' INT
user=`whoami`
if [ $user != 'root' ];then
echo "Please execute the script via root user"
exit 1
fi

sid=`df -h | grep '/sybase/' | awk '{print $NF}' | cut -d / -f3 | head -1`
SID=`echo ${sid} | tr "[A-Z]" "[a-z]"`
sid_first_letter=`df -h | grep '/sybase/' | awk '{print $NF}' | cut -d / -f3 | head -1 | cut -c1`


function operation {
echo -e "*************************************************"
echo -e "Kindly Specify what action needs to be taken :- "
echo -e ""
echo -e "1:- Check the Services Status..?"
echo -e "2:- Start the Complete System (ASE+ Backup Server)..?"
echo -e "3:- Stop the System..?"
echo -e "4:- Exit..?"
echo -e "\n"
echo -e "*************************************************"
read -p "Option: " Input


if [ $Input == "1" ] ; then

echo "Getting the Current Status of ASE system $sid"
echo " "
cd /usr/sap/hostctrl/exe
./saphostctrl -function GetDatabaseStatus -dbname $sid -dbtype SYB |grep --color -E 'Status'

echo " "

elif
[ $Input == "2" ] ; then
 sudo su - syb$SID -c "startserver -f /sybase/$sid/ASE-16_0/install/RUN_$sid  -f /sybase/$sid/ASE-16_0/install/RUN_"$sid"_BS"
 exit 0

 elif
 [ $Input == "3" ] ; then

 echo " You are Going to Stop $sid system...Confirm Yes/No"
 echo " "
 read -p "Enter Yes/No(Case Sensitive) : " Inp

                                 if [[ $Inp = "Yes" ]]; then
                                                                 echo  "You have Given Yes, Proceeding Further...!"

                                                                 sudo su - syb$SID -c "isql -k DBA -X -i /usr/sap/ASE_SCRIPTS/stop.sql "
                                                                 exit 0

                                                                                                 elif [[ $Inp = "No" ]]; then
                                                                                                                                 echo "You have Given No,exiting the script....!"
                                                                                                                                                                 exit 1
                                                                                                                                                                                                 else
                                                                                                                                                                                                                                 echo "Invaild response!!, exiting the script ...!"
                                                                                                                                                                                                                                                                 exit 1
                                                                                                                                                                                                                                                                                                 fi
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 exit 0
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 elif
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 [ $Input == "4" ] ; then
                                                                                                                                                                                                                                                                                                 echo -e "\n"
                                                                                                                                                                                                                                                                                                 echo -e "Exiting the script ,bye!!"
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 else
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                 echo -e "\n"
                                                                                                                                                                                                                                                                                                 echo -e "Seems you have selected wrong option ,try again"
                                                                                                                                                                                                                                                                                                 fi
                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                 if [ $sid_first_letter == "P" ] ; then
                                                                                                                                                                                                                                                                                                 echo -e "****************************************************************************"
                                                                                                                                                                                                                                                                                                 echo -e "You are in Production System $sid. Are you sure you want to proceed further ..?"
                                                                                                                                                                                                                                                                                                 echo -e "****************************************************************************"
                                                                                                                                                                                                                                                                                                 echo " "
                                                                                                                                                                                                                                                                                                 read -p "Enter Yes/No(Case Sensitive) : " In
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                 if [[ $In = "Yes" ]]; then
                                                                                                                                                                                                                                                                                                                                                                 echo  "You have Given Yes, Proceeding Further...!"
                                                                                                                                                                                                                                                                                                                                                                                                 operation
                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                 elif [[ $In = "No" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo "You have Given No,exiting the script....!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 exit 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo "Invaild response!!, exiting the script ...!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 exit 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo -e "*******************************"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo -e "You are in  System $sid ...!!!!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo -e "*******************************"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 echo " "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 operation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
